Repository RoBorregos/home-manipulation, pull requests merged in 2024-04, with the labels that each got.

#13 Multiple server intialization
  .gitignore
  ws/src/cartesian_movement_services/scripts/cartesian_server.py
Labels: enhancement

#14 Cartesian pick and place first implementation
  ws/src/cartesian_movement_services/arm_scripts/pouring_srv.py
  ws/src/cartesian_movement_services/scripts/cartesian_client.py
  ws/src/cartesian_movement_services/scripts/cartesian_server.py
  ws/src/object_detector_2d/scripts/Detection2D.py
  ws/src/object_detector_3d/src/Clustering_Server.py
  ws/src/object_detector_3d/src/Detection3D.cpp
  ws/src/object_detector_3d/src/Detection3DKmeans.cpp
  ws/src/pick_and_place/config/dashgo_eigen_params_SF.cfg
  ws/src/pick_and_place/config/params_DASHGO.yaml
  ws/src/pick_and_place/launch/cartesian.manipulation.launch
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/robot_description/urdf/dashgo.urdf.xacro
  ws/src/robot_description/urdf/gripper/gripperSF.urdf.xacro
Labels: enhancement

#16 Horizontal Pick and Place
  ws/src/cartesian_movement_services/CMakeLists.txt
  ws/src/cartesian_movement_services/arm_scripts/pouring_srv.py
  ws/src/cartesian_movement_services/scripts/cartesian_client.py
  ws/src/cartesian_movement_services/scripts/cartesian_server.py
  ws/src/cartesian_movement_services/srv/Pour.srv
  ws/src/object_detector_2d/scripts/Detection2D.py
  ws/src/object_detector_3d/action/DetectObjects3D.action
  ws/src/object_detector_3d/src/Detection3D.cpp
  ws/src/pick_and_place/config/params_DASHGO.yaml
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
Labels: enhancement

#17 Manipulation Docker for CPU/CUDA
  Makefile
  README.md
  docker/Dockerfile.manipulation
  docker/Dockerfile.manipulation.cuda
  docker/requirements/manipulation_requirements.txt
  docker/scripts/build.bash
  docker/scripts/run.bash
  ws/src/pick_and_place/config/dashgo_eigen_params_SF.cfg
Labels: feature

#21 Interface Package for Task Manager
  ws/src/frida_manipulation_interfaces/CMakeLists.txt
  ws/src/frida_manipulation_interfaces/action/manipulationPickAndPlace.action
  ws/src/frida_manipulation_interfaces/package.xml
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/pick_and_place/scripts/manipulationClient.py
  ws/src/pick_and_place/scripts/manipulationServer.py
Labels: feature

#22 Add interfaces package to unified roscore branch
  ws/src/frida_manipulation_interfaces/CMakeLists.txt
  ws/src/frida_manipulation_interfaces/action/manipulationPickAndPlace.action
  ws/src/frida_manipulation_interfaces/package.xml
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/pick_and_place/scripts/manipulationClient.py
  ws/src/pick_and_place/scripts/manipulationServer.py
Labels: enhancement

#24 Unify Roscores
  ws/src/dashgo_moveit_config/config/dashgo.srdf
  ws/src/dashgo_moveit_config/launch/dashgo_xarm.launch
  ws/src/dashgo_moveit_config/launch/moveit_rviz_common.launch
  ws/src/dashgo_moveit_config/rviz/rvizManipulation.rviz
  ws/src/pick_and_place/launch/cartesian.manipulation.launch
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/pick_and_place/scripts/manipulationCaller.py
  ws/src/robot_description/urdf/dashgo.urdf.xacro
Labels: enhancement

#31 Pouring methods and pick/place upgrade
  ws/src/cartesian_movement_services/CMakeLists.txt
  ws/src/cartesian_movement_services/arm_scripts/__pycache__/pouring_srv.cpython-38.pyc
  ws/src/cartesian_movement_services/arm_scripts/arm_movements.py
  ws/src/cartesian_movement_services/arm_scripts/pouring_srv.py
  ws/src/cartesian_movement_services/scripts/arm_movements.py
  ws/src/cartesian_movement_services/scripts/cartesian_client.py
  ws/src/cartesian_movement_services/scripts/cartesian_server.py
  ws/src/cartesian_movement_services/scripts/cartesian_server_2.py
  ws/src/cartesian_movement_services/srv/PlaceInShelf.srv
  ws/src/cartesian_movement_services/srv/Pour.srv
  ws/src/frida_manipulation_interfaces/action/manipulationPickAndPlace.action
  ws/src/object_detector_2d/scripts/Detection2D.py
  ws/src/object_detector_3d/src/Clustering_Server.py
  ws/src/pick_and_place/config/params_DASHGO.yaml
  ws/src/pick_and_place/launch/cartesian.manipulation.launch
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/pick_and_place/scripts/manipulationCaller.py
  ws/src/pick_and_place/scripts/manipulationClient.py
Labels: enhancement, feature

#25 Unified Navigation and Manipulation roscores
  ws/src/cartesian_movement_services/CMakeLists.txt
  ws/src/cartesian_movement_services/arm_scripts/__pycache__/pouring_srv.cpython-38.pyc
  ws/src/cartesian_movement_services/arm_scripts/arm_movements.py
  ws/src/cartesian_movement_services/arm_scripts/pouring_srv.py
  ws/src/cartesian_movement_services/scripts/arm_movements.py
  ws/src/cartesian_movement_services/scripts/cartesian_client.py
  ws/src/cartesian_movement_services/scripts/cartesian_server.py
  ws/src/cartesian_movement_services/scripts/cartesian_server_2.py
  ws/src/cartesian_movement_services/srv/PlaceInShelf.srv
  ws/src/cartesian_movement_services/srv/Pour.srv
  ws/src/dashgo_moveit_config/config/dashgo.srdf
  ws/src/dashgo_moveit_config/launch/dashgo_xarm.launch
  ws/src/dashgo_moveit_config/launch/moveit_rviz_common.launch
  ws/src/dashgo_moveit_config/rviz/rvizManipulation.rviz
  ws/src/frida_manipulation_interfaces/CMakeLists.txt
  ws/src/frida_manipulation_interfaces/action/manipulationPickAndPlace.action
  ws/src/frida_manipulation_interfaces/package.xml
  ws/src/object_detector_2d/scripts/Detection2D.py
  ws/src/object_detector_3d/src/Clustering_Server.py
  ws/src/pick_and_place/config/params_DASHGO.yaml
  ws/src/pick_and_place/launch/cartesian.manipulation.launch
  ws/src/pick_and_place/scripts/cartesianManipulationServer.py
  ws/src/pick_and_place/scripts/manipulationCaller.py
  ws/src/pick_and_place/scripts/manipulationClient.py
  ws/src/pick_and_place/scripts/manipulationServer.py
  ws/src/robot_description/urdf/dashgo.urdf.xacro
Labels: enhancement

#36 Added L4T 35.4.1 docker image for moveit config.
  Makefile
  docker/Dockerfile.manipulation.l4t-35.4.1
  docker/requirements/manipulation_requirements.txt
Labels: enhancement

#37 TMR2024 Developments
  Makefile
  docker/Dockerfile.manipulation.l4t-35.4.1
  docker/requirements/manipulation_requirements.txt
  ws/src/dashgo_moveit_config/config/dashgo.srdf
  ws/src/dashgo_moveit_config/launch/dashgo_xarm.launch
  ws/src/dashgo_moveit_config/rviz/rvizManipulation.rviz
  ws/src/frida_arm_joints_server/CMakeLists.txt
  ws/src/frida_arm_joints_server/package.xml
  ws/src/frida_arm_joints_server/scripts/arm_joint_server.py
  ws/src/frida_manipulation_interfaces/CMakeLists.txt
  ws/src/frida_manipulation_interfaces/action/MoveJoint.action
  ws/src/frida_manipulation_interfaces/srv/Gripper.srv
  ws/src/object_detector_3d/images/clusters.png
Labels: enhancement, release
